### ISSUE TITLE
Add support of $TOPICS parameter

### ISSUE THREAD

**Issue by msangel** [wlsc/docker-kafka#2]
This is a feature request.
Sometimes for development it's required that certain kafka topic already exists there, otherwise clients will throw en exception upon connection to it (see: google.com/search?q=Topic(s)+%5ByourTopicName%5D+is%2Fare+not+present+and+missingTopicsFatal+is+true).
Having this parameter, the container will ready to accept client connections once the topic will be created. 
Thanks!

**Comment by wlsc** [comment]
hi @msangel ! thanks for the feature request. I've found some free time to add such feature here https://github.com/wlsc/docker-kafka/pull/3

**Comment by wlsc** [comment]
these changes are now available in 3.3.1-kraft version and latest
